openapi: 3.0.0
info:
  title: Athenix API
  version: 1.0.0
servers:
  - url: 'https://athenix.bcserver.xyz'
    description: Athenix dev api
  - url: 'https://api.athenix.ai'
    description: Athenix Prod api
components:
  securitySchemes:
    API_TOKEN:
      name: API_TOKEN
      type: apiKey
      in: header
  schemas:
    Product:
      title: Product
      x-stoplight:
        id: 8ydxjxwgyklbn
      type: object
      x-examples:
        Product with all variants:
          id: '35123512352'
          variant: ALL
          totalVariant: 0
        'Product with specific variants ':
          id: '35123512352'
          variant:
            - '23523523523'
            - '32523523223'
          totalVariant: 3
      required:
        - id
        - variant
        - totalVariant
      properties:
        id:
          type: string
          x-stoplight:
            id: j5cm8g7omgto9
          example: '35123512352'
        variant:
          type:
            - array
            - string
          x-stoplight:
            id: 8cge1xxrygmz2
          items: {}
        totalVariant:
          type: number
          x-stoplight:
            id: m49svle29s28d
      description: ''
paths:
  '/v1/recommend/{recommenderType}/trigger':
    post:
      tags:
        - default
      summary: Trigger write metafield for products
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - shopId
                - originalProduct
              properties:
                excludeProducts:
                  type: array
                  x-stoplight:
                    id: ffi3rryw5j9rm
                  description: exclude product ids
                  items:
                    $ref: '#/components/schemas/Product'
                shopId:
                  type: string
                  x-stoplight:
                    id: uqy9ooa8f1907
                  example: '23512351235125'
                originalProduct:
                  type: object
                  x-stoplight:
                    id: zojmc35hnkp4i
                  required:
                    - type
                  properties:
                    type:
                      x-stoplight:
                        id: 8cf3qp0np2rst
                      enum:
                        - all
                        - collections
                        - tags
                        - specific
                    items:
                      type:
                        - array
                        - string
                      x-stoplight:
                        id: 2xhwjh1ucdpfu
                      items: {}
            examples:
              Register with all products:
                value:
                  excludeProducts:
                    - id: '35123512352'
                      variant: ALL
                      totalVariant: 0
                    - id: '35123512352'
                      variant:
                        - '35235235'
                        - '352352'
                      totalVariant: 3
                  shopId: '23512351235125'
                  originalProduct:
                    type: all
                    items: []
              Register with collections:
                value:
                  excludeProducts:
                    - id: '35123512352'
                      variant: ALL
                      totalVariant: 0
                    - id: '35123512352'
                      variant:
                        - '35235235'
                        - '352352'
                      totalVariant: 3
                  shopId: '23512351235125'
                  originalProduct:
                    type: collections
                    items:
                      - '23512351235125'
                      - '84512351235235'
              Register with products tags:
                value:
                  excludeProducts:
                    - id: '35123512352'
                      variant: ALL
                      totalVariant: 0
                    - id: '35123512352'
                      variant:
                        - '35235235'
                        - '352352'
                      totalVariant: 3
                  shopId: '23512351235125'
                  originalProduct:
                    type: tags
                    items:
                      - adidas
                      - autumn
                      - summer
              Register with specific products:
                value:
                  excludeProducts:
                    - id: '35123512352'
                      variant: ALL
                      totalVariant: 0
                    - id: '35123512352'
                      variant:
                        - '35235235'
                        - '352352'
                      totalVariant: 3
                  shopId: '23512351235125'
                  originalProduct:
                    type: specific
                    items:
                      - id: '35123512352'
                        variant: ALL
                        totalVariant: 5
                      - id: '35123512323'
                        variant:
                          - '35235235'
                          - '352352'
                        totalVariant: 3
      security:
        - API_TOKEN: []
      parameters: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    x-stoplight:
                      id: c3kn7wuhckano
                    example: successfully
              examples:
                Example 1:
                  value:
                    message: successfully
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    x-stoplight:
                      id: ibjgavc9nzesc
      operationId: ''
      x-stoplight:
        id: t3e9eizpislfh
    parameters:
      - schema:
          type: string
          example: fbt
          enum:
            - fbt
        name: recommenderType
        in: path
        required: true
